boilerplate

diff --git a/.github/workflows/boilerplate.yml b/.github/workflows/boilerplate.yml
--- a/.github/workflows/boilerplate.yml
+++ b/.github/workflows/boilerplate.yml
@@ -13,3 +13,88 @@
 # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 # See the License for the specific language governing permissions and
 # limitations under the License.
+
+name: boilerplate
+
+on: pull_request
+
+jobs:
+  boilerplate:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check out head
+        uses: actions/checkout@v3
+        with:
+          fetch-depth: 0
+      - name: Get changed files
+        id: changed-files
+        uses: tj-actions/changed-files@v31
+        with:
+          files: |
+            **/*.py
+      - name: Boilerplate
+        env:
+          boilerplate2021: |-
+            # Copyright 2021 Agnostiq Inc.
+            #
+            # This file is part of Covalent.
+            #
+            # Licensed under the Apache License 2.0 (the "License"). A copy of the
+            # License may be obtained with this software package or at
+            #
+            #     https://www.apache.org/licenses/LICENSE-2.0
+            #
+            # Use of this file is prohibited except in compliance with the License.
+            # Unless required by applicable law or agreed to in writing, software
+            # distributed under the License is distributed on an "AS IS" BASIS,
+            # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+            # See the License for the specific language governing permissions and
+            # limitations under the License.
+
+          boilerplate2022: |-
+            # Copyright 2022 Agnostiq Inc.
+            #
+            # This file is part of Covalent.
+            #
+            # Licensed under the Apache License 2.0 (the "License"). A copy of the
+            # License may be obtained with this software package or at
+            #
+            #     https://www.apache.org/licenses/LICENSE-2.0
+            #
+            # Use of this file is prohibited except in compliance with the License.
+            # Unless required by applicable law or agreed to in writing, software
+            # distributed under the License is distributed on an "AS IS" BASIS,
+            # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+            # See the License for the specific language governing permissions and
+            # limitations under the License.
+
+          boilerplate2023: |-
+            # Copyright 2023 Agnostiq Inc.
+            #
+            # This file is part of Covalent.
+            #
+            # Licensed under the Apache License 2.0 (the "License"). A copy of the
+            # License may be obtained with this software package or at
+            #
+            #     https://www.apache.org/licenses/LICENSE-2.0
+            #
+            # Use of this file is prohibited except in compliance with the License.
+            # Unless required by applicable law or agreed to in writing, software
+            # distributed under the License is distributed on an "AS IS" BASIS,
+            # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+            # See the License for the specific language governing permissions and
+            # limitations under the License.
+
+        run: |
+          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
+            if [[ ! $( cat $file | tr -d '\r' ) =~ "$boilerplate2021" && ! $( cat $file | tr -d '\r' ) =~ "$boilerplate2022" && ! $( cat $file | tr -d '\r' ) =~ "$boilerplate2023" ]] ; then
+              printf "Boilerplate is missing from $file.\n"
+              printf "The first 20 lines of $file are\n\n"
+              cat $file | tr -d '\r' | cat -ET | head -n 20
+              printf "\nThe boilerplate should be\n\n"
+              echo "$boilerplate" | cat -ET
+              printf "\nThe diff is\n\n"
+              diff <(cat $file | tr -d '\r' | head -n 20) <(echo "$boilerplate") | cat -ET
+              exit 1
+            fi
+          done
