fixing

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -193,7 +193,17 @@ jobs:
 
       - name: Build Stable or Pre-Release Distribution
         id: pre-or-stable-build
-        run: python setup.py sdist
+        run: |
+          if [ "${{ inputs.prerelease }}" = "false" ] && [ -z "${{ github.event.inputs.stable_version }}" ]; then
+            echo "You can't create a stable release without specifying the stable version number."
+            exit 1
+          fi
+          if [ "${{ inputs.prerelease }}" = "false" ] && [ -n "${{ github.event.inputs.stable_version }}" ]; then
+            VERSION="${{ github.event.inputs.stable_version }}"
+            # Change the VERSION file here to the stable version
+            echo "$VERSION" > VERSION
+          fi
+          python setup.py sdist
 
       - name: Transform semver version to pep440
         id: version-transform
@@ -204,11 +214,6 @@ jobs:
       - name: Validate Distribution
         id: validate
         run: |
-          if [ -z ${{ inputs.prerelease }} ] && \
-             [ -z ${{ github.event.inputs.stable_version }} ] ; then
-            echo "You can't create a stable release without specifying the stable version number."
-            exit 1
-          fi
           VERSION="${{ steps.version-transform.outputs.version }}"
           cd dist
           tar xzf covalent-${VERSION}.tar.gz
