cleaning up release workflow

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -21,7 +21,6 @@
 name: release
 
 on:
-  pull_request:
   workflow_dispatch:
     inputs:
       stable_version:
@@ -56,6 +55,218 @@ env:
   AWS_PLUGINS_VERSION_URL: "https://raw.githubusercontent.com/AgnostiqHQ/covalent-aws-plugins/develop/VERSION?token=${{ secrets.COVALENT_OPS_BOT_TOKEN }}"
 
 jobs:
+  github:
+    runs-on: ubuntu-latest
+    outputs:
+      release: ${{ env.RELEASE }}
+    steps:
+      - name: Check out stable release tag
+        uses: actions/checkout@v2
+        if: github.event.inputs.stable_version
+        with:
+          persist-credentials: false
+          fetch-depth: 0
+          ref: "v${{ github.event.inputs.stable_version }}"
+      - name: Format prerelease ref
+        if: inputs.prerelease
+        run: |
+          re='^[0-9]+$'
+          IFS='.' read -ra version <<< "${{ inputs.prerelease_version }}"
+          if [[ ${version[0]} =~ $re ]] ; then
+            echo "PRERELEASE=v$version" >> $GITHUB_ENV
+          else
+            echo "PRERELEASE=$version" >> $GITHUB_ENV
+          fi
+      - name: Check out prerelease tag
+        uses: actions/checkout@v2
+        if: inputs.prerelease
+        with:
+          persist-credentials: false
+          fetch-depth: 0
+          ref: "${{ env.PRERELEASE }}"
+      - name: Generate stable release message
+        if: >
+          github.event.inputs.stable_version
+          && contains(env.PAUL_BLART, github.actor)
+        id: stable-changelog
+        uses: AgnostiqHQ/covalent/.github/actions/stable-changelog@develop
+        with:
+          changelog-path: CHANGELOG.md
+          version-path: VERSION
+
+      - name: Read version
+        run: |
+          if [ -z ${{ inputs.prerelease }} ] && \
+             [ -z ${{ github.event.inputs.stable_version }} ] ; then
+            echo "You can't create a stable release without specifying the stable version number."
+            exit 1
+          fi
+          VERSION="$(cat ./VERSION)"
+          echo "VERSION=$VERSION" >> $GITHUB_ENV
+          echo "RELEASE=v$VERSION" >> $GITHUB_ENV
+      - name: Generate prerelease message
+        if: inputs.prerelease
+        id: message
+        run: |
+          begin=$(grep -n "\b${VERSION}\b" ./CHANGELOG.md | cut -d ':' -f 1)
+          previous_version=$(git describe --abbrev=0 $RELEASE^ | cut -c2-)
+          end=$(tail -n +$((begin+1)) ./CHANGELOG.md | grep -n -m 1 "\b${previous_version}\b" | cut -d ':' -f 1)
+          echo 'MESSAGE<<EOF' >> $GITHUB_ENV
+          tail +$begin ./CHANGELOG.md | head -$end >> $GITHUB_ENV
+          echo 'EOF' >> $GITHUB_ENV
+      - name: Tag commit
+        id: push
+        continue-on-error: true
+        run: |
+          git config user.name "CovalentOpsBot"
+          git config user.email "covalentopsbot@users.noreply.github.com"
+          git tag -a $RELEASE -m "Release $RELEASE"
+          git remote set-url origin https://${{ secrets.COVALENT_OPS_BOT_TOKEN }}@github.com/AgnostiqHQ/covalent.git
+          git push origin $RELEASE
+      - name: Create prerelease
+        if: >-
+          inputs.prerelease
+          && steps.message.outcome == 'success'
+          && (!github.event.inputs.test_release || github.event.inputs.test_release == 'false')
+        uses: ncipollo/release-action@v1
+        with:
+          body: ${{ env.MESSAGE }}
+          token: ${{ secrets.COVALENT_OPS_BOT_TOKEN }}
+          tag: ${{ env.RELEASE }}
+          prerelease: true
+      - name: Create stable release
+        if: >-
+          github.event.inputs.stable_version
+          && contains(env.PAUL_BLART, github.actor)
+          && steps.stable-changelog.outcome == 'success'
+          && (!github.event.inputs.test_release || github.event.inputs.test_release == 'false')
+        uses: ncipollo/release-action@v1
+        with:
+          body: ${{ steps.stable-changelog.outputs.message }}
+          token: ${{ secrets.COVALENT_OPS_BOT_TOKEN }}
+          tag: ${{ env.RELEASE }}
+      - name: Alert Slack
+        if: failure()
+        uses: rtCamp/action-slack-notify@v2
+        env:
+          SLACK_CHANNEL: "covalent-ci"
+          SLACK_USERNAME: "CovalentOpsBot"
+          SLACK_MESSAGE: "The release.yml workflow is failing in ${{ github.ref }}!"
+          SLACK_COLOR: ${{ job.status }}
+          SLACK_TITLE: ":warning:  Attention Required  :warning:"
+          SLACK_WEBHOOK: ${{ secrets.SLACK_ALERT_WEBHOOK }}
+
+  pypi:
+    runs-on: ubuntu-latest
+    needs: github
+    outputs:
+      version: ${{ steps.validate.outputs.version }}
+    steps:
+      - name: Check out release tag
+        uses: actions/checkout@v2
+        with:
+          persist-credentials: false
+          fetch-depth: 0
+          ref: ${{ needs.github.outputs.release }}
+      - name: Set up Python
+        uses: actions/setup-python@v2
+        with:
+          python-version: 3.8
+      - name: Install Python dependencies
+        run: |
+          python -m pip install --upgrade pip
+          pip install twine
+      - name: Set up Node
+        uses: actions/setup-node@v2
+        with:
+          node-version: 16
+      - name: Build Webapp
+        run: |
+          cd ./covalent_ui/webapp
+          yarn install
+          yarn build
+      - name: Build Stable or Pre-Release Distribution
+        id: pre-or-stable-build
+        run: python setup.py sdist
+      - name: Transform semver version to pep440
+        id: version-transform
+        uses: ./.github/actions/version-transform
+        with:
+          version-path: VERSION
+      - name: Validate Distribution
+        id: validate
+        run: |
+          if [ -z ${{ inputs.prerelease }} ] && \
+             [ -z ${{ github.event.inputs.stable_version }} ] ; then
+            echo "You can't create a stable release without specifying the stable version number."
+            exit 1
+          fi
+          VERSION="${{ steps.version-transform.outputs.version }}"
+          cd dist
+          tar xzf covalent-${VERSION}.tar.gz
+          diff -x .gitignore -r covalent-${VERSION}/covalent ../covalent
+          diff -x .gitignore -r covalent-${VERSION}/covalent_dispatcher ../covalent_dispatcher
+          diff -x README.md -r covalent-${VERSION}/covalent_migrations ../covalent_migrations
+          diff -x .gitignore -x README.md -x webapp covalent-${VERSION}/covalent_ui ../covalent_ui
+          diff -r covalent-${VERSION}/covalent_ui/webapp/build ../covalent_ui/webapp/build
+          rm -rf covalent-${VERSION}/
+          echo "::set-output name=version::$VERSION"
+      - name: Upload Distribution
+        if: >
+          steps.pre-or-stable-build.outcome == 'success'
+          && steps.validate.outcome == 'success'
+          && ${{ !github.event.inputs.test_release }}
+        env:
+          TWINE_USERNAME: __token__
+          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
+        run: twine upload dist/*
+      - name: Alert Slack
+        if: failure()
+        uses: rtCamp/action-slack-notify@v2
+        env:
+          SLACK_CHANNEL: "covalent-ci"
+          SLACK_USERNAME: "CovalentOpsBot"
+          SLACK_MESSAGE: "The release.yml workflow is failing in ${{ github.ref }}!"
+          SLACK_COLOR: ${{ job.status }}
+          SLACK_TITLE: ":warning:  Attention Required  :warning:"
+          SLACK_WEBHOOK: ${{ secrets.SLACK_ALERT_WEBHOOK }}
+
+  conda:
+    needs: pypi
+    runs-on: ubuntu-latest
+    strategy:
+      fail-fast: false
+      matrix:
+        python-version:
+          - "3.8"
+          - "3.9"
+          - "3.10"
+    steps:
+      - name: Check for stable release
+        if: github.event.inputs.stable_version && !inputs.prerelease
+        run: echo "STABLE=true" >> $GITHUB_ENV
+      - name: Conda skeleton publish
+        uses: AgnostiqHQ/conda-skeleton-publish@main
+        if: ${{ !github.event.inputs.test_release }}
+        with:
+          pypi_package: "covalent"
+          python_version: ${{ matrix.python-version }}
+          upload_channel: "agnostiq"
+          access_token: ${{ secrets.ANACONDA_TOKEN }}
+          package_version: ${{ needs.pypi.outputs.version }}
+          stable: ${{ env.STABLE }}
+          wait: true
+      - name: Alert Slack
+        if: failure()
+        uses: rtCamp/action-slack-notify@v2
+        env:
+          SLACK_CHANNEL: "covalent-ci"
+          SLACK_USERNAME: "CovalentOpsBot"
+          SLACK_MESSAGE: "The release.yml workflow is failing in ${{ github.ref }}!"
+          SLACK_COLOR: ${{ job.status }}
+          SLACK_TITLE: ":warning:  Attention Required  :warning:"
+          SLACK_WEBHOOK: ${{ secrets.SLACK_ALERT_WEBHOOK }}
+
   docker:
     runs-on: ubuntu-latest
     permissions:
