reverted pypi comment

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -154,78 +154,78 @@ jobs:
       #     SLACK_TITLE: ":warning:  Attention Required  :warning:"
       #     SLACK_WEBHOOK: ${{ secrets.SLACK_ALERT_WEBHOOK }}
 
-  # pypi:
-  #   runs-on: ubuntu-latest
-  #   needs: github
-  #   outputs:
-  #     version: ${{ steps.validate.outputs.version }}
-  #   steps:
-  #     - name: Check out release tag
-  #       uses: actions/checkout@v4
-  #       with:
-  #         persist-credentials: false
-  #         fetch-depth: 0
-  #         ref: ${{ needs.github.outputs.release }}
+  pypi:
+    runs-on: ubuntu-latest
+    needs: github
+    outputs:
+      version: ${{ steps.validate.outputs.version }}
+    steps:
+      - name: Check out release tag
+        uses: actions/checkout@v4
+        with:
+          persist-credentials: false
+          fetch-depth: 0
+          ref: ${{ needs.github.outputs.release }}
 
-  #     - name: Set up Python
-  #       uses: actions/setup-python@v2
-  #       with:
-  #         python-version: "3.10"
+      - name: Set up Python
+        uses: actions/setup-python@v2
+        with:
+          python-version: "3.10"
 
-  #     - name: Install Python dependencies
-  #       run: |
-  #         python -m pip install --upgrade pip
-  #         pip install twine
+      - name: Install Python dependencies
+        run: |
+          python -m pip install --upgrade pip
+          pip install twine
 
-  #     - name: Set up Node
-  #       uses: actions/setup-node@v2
-  #       with:
-  #         node-version: 20
+      - name: Set up Node
+        uses: actions/setup-node@v2
+        with:
+          node-version: 20
 
-  #     - name: Build Webapp
-  #       run: |
-  #         cd ./covalent_ui/webapp
-  #         yarn install
-  #         yarn build
+      - name: Build Webapp
+        run: |
+          cd ./covalent_ui/webapp
+          yarn install
+          yarn build
 
-  #     - name: Build Stable or Pre-Release Distribution
-  #       id: pre-or-stable-build
-  #       run: python setup.py sdist
+      - name: Build Stable or Pre-Release Distribution
+        id: pre-or-stable-build
+        run: python setup.py sdist
 
-  #     - name: Transform semver version to pep440
-  #       id: version-transform
-  #       uses: ./.github/actions/version-transform
-  #       with:
-  #         version-path: VERSION
+      - name: Transform semver version to pep440
+        id: version-transform
+        uses: ./.github/actions/version-transform
+        with:
+          version-path: VERSION
 
-  #     - name: Validate Distribution
-  #       id: validate
-  #       run: |
-  #         if [ -z ${{ inputs.prerelease }} ] && \
-  #            [ -z ${{ github.event.inputs.stable_version }} ] ; then
-  #           echo "You can't create a stable release without specifying the stable version number."
-  #           exit 1
-  #         fi
-  #         VERSION="${{ steps.version-transform.outputs.version }}"
-  #         cd dist
-  #         tar xzf covalent-${VERSION}.tar.gz
-  #         diff -x .gitignore -r covalent-${VERSION}/covalent ../covalent
-  #         diff -x .gitignore -r covalent-${VERSION}/covalent_dispatcher ../covalent_dispatcher
-  #         diff -x README.md -r covalent-${VERSION}/covalent_migrations ../covalent_migrations
-  #         diff -x .gitignore -x README.md -x webapp covalent-${VERSION}/covalent_ui ../covalent_ui
-  #         diff -r covalent-${VERSION}/covalent_ui/webapp/build ../covalent_ui/webapp/build
-  #         rm -rf covalent-${VERSION}/
-  #         echo "::set-output name=version::$VERSION"
+      - name: Validate Distribution
+        id: validate
+        run: |
+          if [ -z ${{ inputs.prerelease }} ] && \
+             [ -z ${{ github.event.inputs.stable_version }} ] ; then
+            echo "You can't create a stable release without specifying the stable version number."
+            exit 1
+          fi
+          VERSION="${{ steps.version-transform.outputs.version }}"
+          cd dist
+          tar xzf covalent-${VERSION}.tar.gz
+          diff -x .gitignore -r covalent-${VERSION}/covalent ../covalent
+          diff -x .gitignore -r covalent-${VERSION}/covalent_dispatcher ../covalent_dispatcher
+          diff -x README.md -r covalent-${VERSION}/covalent_migrations ../covalent_migrations
+          diff -x .gitignore -x README.md -x webapp covalent-${VERSION}/covalent_ui ../covalent_ui
+          diff -r covalent-${VERSION}/covalent_ui/webapp/build ../covalent_ui/webapp/build
+          rm -rf covalent-${VERSION}/
+          echo "::set-output name=version::$VERSION"
 
-  #     - name: Upload Distribution
-  #       if: >
-  #         steps.pre-or-stable-build.outcome == 'success'
-  #         && steps.validate.outcome == 'success'
-  #         && ${{ !github.event.inputs.test_release }}
-  #       env:
-  #         TWINE_USERNAME: __token__
-  #         TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
-  #       run: twine upload dist/*
+      - name: Upload Distribution
+        if: >
+          steps.pre-or-stable-build.outcome == 'success'
+          && steps.validate.outcome == 'success'
+          && ${{ !github.event.inputs.test_release }}
+        env:
+          TWINE_USERNAME: __token__
+          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
+        run: twine upload dist/*
 
       # TODO(sankalp): Need to fix this step, but can be skipped for now
       # - name: Alert Slack
