add pypi job to release.yml

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -38,7 +38,7 @@ on:
         default: true
 
 jobs:
-  release:
+  github:
     runs-on: ubuntu-latest
     steps:
       - name: Check out release tag
@@ -56,6 +56,11 @@ jobs:
           fetch-depth: 0
       - name: Read version
         run: |
+          if [ ${{ github.event.inputs.prerelease }} = 'false' ] && \
+             [ -z ${{ github.event.inputs.stable_version }} ] ; then
+            echo "You can't create a stable release without specifying the stable version number."
+            exit 1
+          fi
           VERSION="$(cat ./VERSION)"
           echo "VERSION=$VERSION" >> $GITHUB_ENV
           echo "RELEASE=v$VERSION" >> $GITHUB_ENV
@@ -77,7 +82,7 @@ jobs:
           tail +$begin ./CHANGELOG.md | head -$end >> $GITHUB_ENV
           echo 'EOF' >> $GITHUB_ENV
       - name: Create release
-        if: ${{ steps.push.outcome == 'success' && steps.message.outcome == 'success' }}
+        if: steps.push.outcome == 'success' && steps.message.outcome == 'success' && github.event.inputs.test_release == 'false'
         uses: ncipollo/release-action@v1
         with:
           body: ${{ env.MESSAGE }}
@@ -91,6 +96,79 @@ jobs:
           SLACK_CHANNEL: "covalent"
           SLACK_USERNAME: "CovalentOpsBot"
           SLACK_MESSAGE: "The release.yml workflow is failing in ${{ github.ref }}!"
+          SLACK_COLOR: ${{ job.status }}
+          SLACK_TITLE: ":warning:  Attention Required  :warning:"
+          SLACK_WEBHOOK: ${{ secrets.SLACK_ALERT_WEBHOOK }}
+  pypi:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check out release tag
+        uses: actions/checkout@v2
+        if: github.event.inputs.prerelease == 'false' && github.event.inputs.stable_version
+        with:
+          persist-credentials: false
+          fetch-depth: 0
+          ref: "v${{ github.event.inputs.stable_version }}"
+      - name: Check out master
+        uses: actions/checkout@v2
+        if: github.event.inputs.prerelease == 'true'
+        with:
+          persist-credentials: false
+          fetch-depth: 0
+      - name: Set up Python
+        uses: actions/setup-python@v2
+        with:
+          python-version: 3.8
+      - name: Install Python dependencies
+        run: |
+          python -m pip install --upgrade pip
+          pip install twine
+      - name: Set up Node
+        uses: actions/setup-node@v2
+        with:
+          node-version: 16
+      - name: Build Webapp
+        run: |
+          cd ./covalent_ui/webapp
+          yarn install
+          yarn build
+      - name: Build Prerelease Distribution
+        if: github.event.inputs.prerelease == 'true'
+        run: python setup.py egg_info --tag-build=pre sdist
+      - name: Build Stable Distribution
+        if: github.event.inputs.prerelease == 'false' && github.event.inputs.stable_version
+        run: python setup.py sdist
+      - name: Validate Distribution
+        run: |
+          if [ ${{ github.event.inputs.prerelease }} = 'false' ] && \
+             [ -z ${{ github.event.inputs.stable_version }} ] ; then
+            echo "You can't create a stable release without specifying the stable version number."
+            exit 1
+          fi
+          VERSION="$(cat ./VERSION)"
+          cd dist
+          tar xzf cova-${VERSION}rc0.tar.gz
+          diff -x tests -r cova-${VERSION}rc0/covalent ../covalent
+          diff -x tests -r cova-${VERSION}rc0/covalent_dispatcher ../covalent_dispatcher
+          diff -x tests -r cova-${VERSION}rc0/covalent_data ../covalent_data
+          diff -x tests -r cova-${VERSION}rc0/covalent_queuer ../covalent_queuer
+          diff -x tests -r cova-${VERSION}rc0/covalent_results ../covalent_results
+          diff -x README.md -x tests -x webapp cova-${VERSION}rc0/covalent_ui ../covalent_ui 
+          diff -r cova-${VERSION}rc0/covalent_ui/webapp/build ../covalent_ui/webapp/build
+          rm -rf cova-${VERSION}rc0/
+      - name: Upload Distribution
+        if: github.event.inputs.test_release == 'false'
+        env:
+          TWINE_USERNAME: __token__
+          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
+        run: twine upload dist/*
+      - name: Alert Slack
+        if: failure()
+        uses: rtCamp/action-slack-notify@v2
+        env:
+          SLACK_CHANNEL: "covalent"
+          SLACK_USERNAME: "CovalentOpsBot"
+          SLACK_MESSAGE: "The pypi.yml workflow is failing in master!"
           SLACK_COLOR: ${{ job.status }}
           SLACK_TITLE: ":warning:  Attention Required  :warning:"
           SLACK_WEBHOOK: ${{ secrets.SLACK_ALERT_WEBHOOK }}
